version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-api
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - sqlserver
    networks:
      - backend

networks:
  backend:
